# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Walker Chapel Preschool
email: wcpreschool@comcast.net
description: >- # this means to ignore newlines until "baseurl:"
  Your Neighborhood school, serving the community since 1970.
  Our program fosters educational, physical, social and emotional
  development through both unstructured and organized play.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: "http://www.walkerchapel.org/Portals/67/Images/Preschool/WCP%20Logo%20-%20transparent%20-%20full.png"
#twitter_username: jekyllrb
#github_username:  jekyll

navigation_header:
  Home: /
  About Us: /about.html
  Admissions: /admissions.html
  Tuition: /tuition.html
  Our Classes: /classroom.html
  Current Families: /families.html
  Contact Us: /contact.html

# Footer nav
navigation_footer:
  Back to top: "#top"

# Build settings
theme: alembic-jekyll-theme
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true


exclude:
- README.md
- Gemfile
- Gemfile.lock
- s3_website.yml

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
